### ISSUE TITLE
Remove custom test script (and ts-node) when tsd is updated

### ISSUE THREAD

**Issue by pastelmind** [pastelmind/kolmafia-types#21]
In #20, I added a custom test script (`run-tests.ts`) to work around a limitation in [tsd](https://github.com/SamVerschueren/tsd), our testing tool. Because tsd 0.14.0 does not support the `typesVersions` property in `package.json`, it cannot find our typings when invoked from the shell. Since it does not provide any mechanism for specifying a custom type source, we need to temporarily supply a `types` field in `package.json`.

To work around this, I wrote a tiny Node.js script (`run-tests.ts`) that monkey-patches `package.json` with a `types` field before running `tsd`, then restore the original afterwards. I also installed [ts-node](https://github.com/TypeStrong/ts-node) to avoid an extra compile step when running the script.

The `main` branch of tsd has recently gained [support for custom type sources.](https://github.com/SamVerschueren/tsd/pull/74)  [Another PR adds an accompanying CLI option for this](https://github.com/SamVerschueren/tsd/pull/93). If the next release of tsd includes these changes, we may be able to replace this script with an invocation of `tsd --typings-file src/index.d.ts`.

## TODO
- [ ] Wait for a new release of tsd
- [ ] Update tsd
- [ ] Replace custom test script and invoke `tsd` from the command line instead
- [ ] Remove ts-node
